// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB41DNSi4VV27koJbJ-NFLR0m0TyhPEVGM',
    appId: '1:715450184214:web:408988ea1163eb3320bb37',
    messagingSenderId: '715450184214',
    projectId: 'flutter-firebase-notific-f7615',
    authDomain: 'flutter-firebase-notific-f7615.firebaseapp.com',
    storageBucket: 'flutter-firebase-notific-f7615.firebasestorage.app',
    measurementId: 'G-K4EVCN8Y33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsHxKgkw4QVPrV-cn2_8EPZJ2c52L1WJA',
    appId: '1:715450184214:android:529475a544b348f120bb37',
    messagingSenderId: '715450184214',
    projectId: 'flutter-firebase-notific-f7615',
    storageBucket: 'flutter-firebase-notific-f7615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM49mkOZmfOWTe2kFX3d_Tovem1CTDDC4',
    appId: '1:715450184214:ios:3c29cd5d7e86067420bb37',
    messagingSenderId: '715450184214',
    projectId: 'flutter-firebase-notific-f7615',
    storageBucket: 'flutter-firebase-notific-f7615.firebasestorage.app',
    iosBundleId: 'myapp.cli.flutterFirebaseCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM49mkOZmfOWTe2kFX3d_Tovem1CTDDC4',
    appId: '1:715450184214:ios:3c29cd5d7e86067420bb37',
    messagingSenderId: '715450184214',
    projectId: 'flutter-firebase-notific-f7615',
    storageBucket: 'flutter-firebase-notific-f7615.firebasestorage.app',
    iosBundleId: 'myapp.cli.flutterFirebaseCli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB41DNSi4VV27koJbJ-NFLR0m0TyhPEVGM',
    appId: '1:715450184214:web:156de16cf9281f7720bb37',
    messagingSenderId: '715450184214',
    projectId: 'flutter-firebase-notific-f7615',
    authDomain: 'flutter-firebase-notific-f7615.firebaseapp.com',
    storageBucket: 'flutter-firebase-notific-f7615.firebasestorage.app',
    measurementId: 'G-JR4Y3S2KLW',
  );
}
